services:

  # 1. This single container handles ALL database and spatial features
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
#    image: postgis/postgis:16-3.5-alpine
#    container_name: postgis-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" # Changed back to standard 5432 for external tool mapping
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  api-service:
    build: .
    container_name: extra-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db # Connect specifically to the postgis container
      - redis-cache
    environment:
      # POSTGRES / POSTGIS ENV (Pointed directly to postgis-db inside the docker network)
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      # REDIS ENV
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      # MAIL ENV
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_MAIL_HOST=${MAIL_HOST}
      # ALIBABA CLOUD ENV
      - ALIBABA_CLOUD_ACCESS_KEY_ID=${ALIBABA_CLOUD_ACCESS_KEY_ID}
      - ALIBABA_CLOUD_ACCESS_KEY_SECRET=${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
      - ALIBABA_CLOUD_TEST_SIGN_NAME=${ALIBABA_CLOUD_TEST_SIGN_NAME}
      - ALIBABA_CLOUD_SECURITY_TEST_TEMPLATE_CODE=${ALIBABA_CLOUD_SECURITY_TEST_TEMPLATE_CODE}
      # GOOGLE ENV
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # PHYSICAL DEVICE ENV
      - DEVICE_API_URL=${DEVICE_API_URL}
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  pg_data: