spring.application.name=extra

# PostgreSql Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.error.include-message=always

# JPA + SQL init
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=6379

# Mybatis Configuration
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.configuration.map-underscore-to-camel-case=true
#mybatis.mapper-locations=classpath:mappers/**/*.xml

# Mail Configuration
spring.mail.protocol=smtp
spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.debug=true

# Alibaba Cloud Credentials
alibaba.cloud.alibaba.cloud.access-key-id=${ALIBABA_CLOUD_ACCESS_KEY_ID}
alibaba.cloud.alibaba.cloud.access-key-secret=${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
alibaba.cloud.test-template-code=SMS_333877357
alibaba.cloud.test-sign-name=Alicloud321